server:
  port: 8086
  servlet:
    context-path: /lms
lms:
  client:
    key: 352019a6-1c73-11eb-adc1-0242ac120002
spring:
  application:
    name: lms-client-service
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/