server:
  port: 8086
  servlet:
    context-path: /lms
lms:
  client:
    key: 352019a6-1c73-11eb-adc1-0242ac120002
spring:
  application:
    name: lms-client-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/