spring:
  profiles:
    active: dev

server:
  port: 8081
  servlet:
    context-path: /api/auth

---
spring:
  profiles:
    - dev
  application:
    name: lms-auth-service
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles:
    - prod
  application:
    name: lms-auth-service
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
