server:
  port: 8081
  servlet:
    context-path: /api/auth
lms:
  client:
    key: 352019a6-1c73-11eb-adc1-0242ac120002
spring:
  application:
    name: lms-auth-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
