server:
  port: 8082
  servlet:
    context-path: /api
lms:
  client:
    key: 352019a6-1c73-11eb-adc1-0242ac120002
spring:
  application:
    name: lms-book-service
  datasource:
    url: jdbc:h2:mem:lms_books;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-books
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/